version: '3.8'

services:
  postgres-primary:
    image: db_image:latest
    container_name: postgres_primary
    networks:
      postgres_net:
        ipv4_address: 192.168.9.100

  postgres-replica-1:
    image: db_repl_image:latest
    container_name: postgres_replica_1
    environment:
      PGDATA: /var/lib/postgresql/data
    networks:
      postgres_net:
        ipv4_address: 192.168.9.101
    volumes:
      - pg_replica1_data:/var/lib/postgresql/data
    command: ["/usr/local/bin/setup-replica.sh"]

  tg-bot:
    image: bot_image:latest
    container_name: tg_bot
    environment:
      DB_HOST: postgres_primary
      DB_PORT: 5432
      DB_NAME: contacts
      DB_USER: postgres
      DB_PASSWORD: 1234
    networks:
      postgres_net:
        ipv4_address: 192.168.9.102
    depends_on:
      - postgres-primary

networks:
  postgres_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.9.0/24

volumes:
  pg_replica1_data:
  tg_bot_data:
